[package]
name = "dan_server"
version = "0.1.0"
edition = "2021"

[dependencies]
poem = "1.2"
poem-openapi = { version = "3.0.6", features = ["swagger-ui"] }
serde = "1.0.193"
serde_json = "1.0.108"
tokio = { version = "1", features = ["macros", "rt-multi-thread"] }
